version: '3'

services:
  app:
    image: ruby:3.2
    container_name: ruby_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    command: sh -c "bundle install && ruby app.rb"
